FROM node:22

WORKDIR /usr/src/app

# Copy package.json and package-lock.json . This copy line below is actually a kind of a flag. The purpose here is to avoid installation if package.json didn't change.
COPY package*.json ./

# Install all dependencies (including dev dependencies)
# "Docker reuses a layer only if everything in that step AND all previous steps stayed exactly the same."
RUN npm install

# Copy the rest of the app
COPY . .

# The "-- --host" ensures the dev server listens on all interfaces
CMD ["npm", "run", "dev", "--", "--host"]
