

# Build Stage
FROM node:22 AS build
WORKDIR /app

COPY client/package*.json ./
RUN npm ci

COPY client ./

# Inject Vite env from CI build args
ARG VITE_API_BASE
ARG VITE_BASE_PATH

ENV VITE_API_BASE=$VITE_API_BASE
ENV VITE_BASE_PATH=$VITE_BASE_PATH

RUN npm run build


# Nginx Stage
FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Since I am not serving content from the server, I need to use nginx to serve the client.
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80


# A Docker container runs by keeping its main process alive.
# If that process exits, the entire container stops.
# Let's run nginx in the foreground.
CMD ["nginx", "-g", "daemon off;"]
