
services:

  local-postgres-database:
    image: postgres:16-alpine
    env_file:
      - ./env/dev/postgres.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bookden_dev"]
      interval: 5s       # check every 5 seconds
      timeout: 5s        # fail if check takes longer than 5s
      retries: 10        # try 10 times before marking unhealthy



  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      local-postgres-database:
        condition: service_healthy   # Just waiting for the database to start is not enough. We need to wait until it is ready to accept connections.
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - ./env/dev/server.env



  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules



volumes:
  pgdata:
