

FROM node:22 AS build
WORKDIR /app

COPY server/package*.json ./
RUN npm ci

COPY server ./
RUN npm run build

FROM node:22
WORKDIR /app

ENV NODE_ENV=production

# Only want to copy the node_modules and build artifacts from the build stage. Not the source code.
COPY server/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/build ./build

# Expose whatever port your server uses
EXPOSE 3000

# Adjust entrypoint if different
CMD ["node", "build/index.js"]
