name: bookden-prod

services:
  postgres:
    image: postgres:16-alpine
    container_name: bookden-postgres
    restart: always
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookden-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: bookden-redis
    image: redis:7-alpine
    restart: always
    networks:
      - bookden-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    image: imranpavel/bookden-server:latest
    container_name: bookden-server
    restart: always
    env_file:
      - ./env/server.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy   # Just waiting for the database to start is not enough. We need to wait until it is ready to accept connections.
    networks:
      - bookden-network
    ports:
      - '3001:3000'

  client:
    image: imranpavel/bookden-client:latest
    container_name: bookden-client
    restart: always
    depends_on:
      - server
    networks:
      - bookden-network
    ports:
      - '3002:80'


networks:
  bookden-network:  # Let's have an isolated network for the app.
    driver: bridge

volumes:
  postgres_data:
