POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "superadmin1",
    "password": "invalidpassword"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "invaliduser",
    "password": "invalidpassword"
}