


DELETE http://localhost:3000/api/books/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN1c3RvbWVyIiwidXNlcklkIjoyNTgsInVzZXJUeXBlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NjUxODc4MTQsImV4cCI6MTc2NTI3NDIxNH0.UCl6ptm7jcvEmDR-Uj9X1KgPkn_89I39r3hk4UEu3ZA

