
GET http://localhost:3000/api/books
Content-Type: application/json
###


GET http://localhost:3000/api/books/836
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NTIwNDAzNiwiZXhwIjoxNzY1MjkwNDM2fQ.oS6MPPICnlRP2vCHjxiVumkXi4Px-bxxwFjuATZ4KqY



GET http://localhost:3000/api/books/820/cover
Content-Type: application/json


###

GET http://localhost:3000/api/books?tags=LAWYERS_FICTION&tags=horror
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NjQxMzY5MywiZXhwIjoxNzY2NTAwMDkzfQ.GzRgNSou72bFQCWDSYtUP4svR7jfAHov8ZSaNt7dVgo

###

GET http://localhost:3000/api/books/834
Content-Type: application/json


###

GET http://localhost:3000/api/books?priceMin=0&priceMax=225
Content-Type: application/json