
GET http://localhost:3000/api/books?search='hudai'
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NTE4ODk3NiwiZXhwIjoxNzY1Mjc1Mzc2fQ.nqui6fVuB9Oi1PTojs6fqMCYEceTAkRg5fJCpEjlekc


###


GET http://localhost:3000/api/books/836
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NTIwNDAzNiwiZXhwIjoxNzY1MjkwNDM2fQ.oS6MPPICnlRP2vCHjxiVumkXi4Px-bxxwFjuATZ4KqY



GET http://localhost:3000/api/books/820/cover
Content-Type: application/json