


PATCH http://localhost:3000/api/books/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NTA1MDIyMywiZXhwIjoxNzY1MTM2NjIzfQ.5GqnDQkZI0V_eSTwvFRTfQvC88tJnF_9BZOhNlc7RM0

{
    "title": "Mockingbird title updated"
}