DELETE http://localhost:3000/api/users/160
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NDUzNzQ5MSwiZXhwIjoxNzY0NjIzODkxfQ.0m1L-9Vsn27DnfQMWvuMJE1Un4zQxCzAuyUdUz4Ep7U

