GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4xIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NjE0OTk3NjIsImV4cCI6MTc2MTU4NjE2Mn0.UdCCZx21vwSSeET5hd2_UfHuj8JjVWCIKXVONaB_kwE