GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJ1c2VySWQiOjEsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTc2NDM0NDg3NCwiZXhwIjoxNzY0NDMxMjc0fQ.9M0bd8sWh3saSt4Q03O_81cRVd6pAJdZET-tL7BKRQA