POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "customer1",
    "password": "password",
    "email": "customer1@gmail.com",
    "userType": "customer",
    "isActive": true
}