POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4xIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NjE0OTgyOTcsImV4cCI6MTc2MTU4NDY5N30.v_NCp_nlDX4lVRZbt0xojskvZiG9AzKbUgsligxfxak

{
    "username": "admin3",
    "password": "password",
    "email": "admin3@gmail.com",
    "userType": "admin",
    "isActive": true
}