PUT http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVyYWRtaW4xIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NjE1MDAwNzEsImV4cCI6MTc2MTU4NjQ3MX0.XWTmFoZtiAZuUvSomz07EUe3qzIWUvPdsnnmLrCFpL0

{
    "username": "superadmin",
    "password": "password",
    "email": "superadmin@gmail.com"
}