

export const BOOK_COVER_WIDTH_DESKTOP = 20;
export const BOOK_COVER_HEIGHT_DESKTOP = BOOK_COVER_WIDTH_DESKTOP * 1.5;

export const BOOK_COVER_WIDTH_MOBILE = 10;
export const BOOK_COVER_HEIGHT_MOBILE = BOOK_COVER_WIDTH_MOBILE * 1.5;