

DELETE http://localhost:3000/api/books/133/wishlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inppb25fZ2xhZGUiLCJ1c2VySWQiOjEzMywidXNlclR5cGUiOiJjdXN0b21lciIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzcxMTk0NTQxLCJleHAiOjE3NzExOTgxNDF9.QHF5WhPWJw4ouQdpWc1Hhz2CFhwwXKA_GxOkH4EK1CE
