

GET http://localhost:3000/api/books/wishlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inppb25fZ2xhZGUiLCJ1c2VySWQiOjEzMywidXNlclR5cGUiOiJjdXN0b21lciIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzczMjc0MzQ2LCJleHAiOjE3NzMyNzc5NDZ9.sLLSMYZ6n9OdFEAdL8aivUUIIdCDWJrOFw2140xYYNs
