
name: Bookden CI/CD

on:
  push:
    branches:
      - development
      - production
      - automated-deployment # remove later. keeping it now for testing purposes.
  pull_request:
    branches: [development, production]



jobs:

  lint_and_test:
    name: lint and test (server and client)
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'


      - name: Install root deps (for Playwright e2e tests)
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps


      # The idea is to:
      # 1. Generate env files for docker compose
      # 2. Start app in dev mode
      # 3. Lint and test server and client inside Docker containers
      # 4. Run Playwright e2e tests
      # 5. Stop app


      # Generate env files for docker compose
      - name: Generate env files for docker compose
        run: |
          mkdir -p env/dev
          
          echo "POSTGRES_DB=bookden_test" > env/dev/postgres.env
          echo "POSTGRES_USER=${{ secrets.DB_ADMIN }}" >> env/dev/postgres.env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env/dev/postgres.env

          echo "DB_ADMIN=${{ secrets.DB_ADMIN }}" > env/dev/server.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env/dev/server.env
          echo "DB_HOST=local-postgres-database" >> env/dev/server.env
          echo "DB_PORT=5432" >> env/dev/server.env
          echo "TEST_DB_URL=postgresql://${{ secrets.DB_ADMIN }}:${{ secrets.DB_PASSWORD }}@local-postgres-database:5432/bookden_test" >> env/dev/server.env
          echo "PORT=3000" >> env/dev/server.env
          echo "FIRST_SUPERADMIN_USERNAME=${{ secrets.FIRST_SUPERADMIN_USERNAME }}" >> env/dev/server.env
          echo "FIRST_SUPERADMIN_PASSWORD=${{ secrets.FIRST_SUPERADMIN_PASSWORD }}" >> env/dev/server.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> env/dev/server.env
          echo "NODE_ENV=test" >> env/dev/server.env

          echo "VITE_API_BASE=http://localhost:3000/api" > env/dev/client.env
          echo "VITE_BASE_PATH=/" >> env/dev/client.env


      # Start app in dev mode
      - name: Start App (docker compose dev mode)
        run: docker compose -f docker-compose.dev.yml up -d --build --remove-orphans

      

      # Tests of server and client follows below.
      # At the end of this job, we will run Playwright e2e tests on CI host.

      # Server lint and test

      - name: Server Lint (inside Docker)
        run: docker compose -f docker-compose.dev.yml exec -T server npm run lint

      - name: Test server (Running tests inside server container). # It is easier this way. Otherwise will need to create another postgres service on CI level, which is unnecessary.
        run: docker compose -f docker-compose.dev.yml exec -T server npm run test  # -T means no TTY (to avoid interactive mode)

      # End of server lint and test

      # Client lint and test
      
      - name: Client Lint (inside Docker)
        run: docker compose -f docker-compose.dev.yml exec -T client npm run lint

      - name: Client Tests (inside Docker)
        run: docker compose -f docker-compose.dev.yml exec -T client npm run test

      # End of client lint and test


      # Playwright e2e tests

      - name: Wait for server health
        run: |
          echo "Waiting for backend..."
          for i in {1..10}; do
            if curl -s http://localhost:3000/api/health >/dev/null; then
              echo "Backend ready!"
              exit 0
            fi
            echo "Retry..."
            sleep 2
          done
          echo "Backend never became ready"
          exit 1

      - name: Run Playwright E2E
        run: npm run e2e

      # End of Playwright e2e tests

      - name: Stop App
        if: always()
        run: docker compose -f docker-compose.dev.yml down
        
